### ISSUE TITLE
Create an initial implementation of AuthInitialize interface that can connect to PCC

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-boot-data-geode#1]
http://gemfire-82-javadocs.docs.pivotal.io/com/gemstone/gemfire/security/AuthInitialize.html

I think the first hello-world step is an implementation that will pull username/password from a specific environment variable set by the PCC service.  The env-var can be hard coded to use a specific name of the PCC service.

**Comment by jxblum** [comment]
I think the first step for Spring Boot / GemFire support should be auto-configuration of the cache, and a `ClientCache` in particular.

I think the default implementation of the `AuthInitialize` interface should live in _Spring Data GemFire_

Will provide more thoughts and feedback on this shortly.

**Comment by jxblum** [comment]
Just an update to my earlier comment above... 

Since _Spring Data_ **Kay** (i.e. _Spring Data GemFire_ **2.0**), I have added first-class support for both Pivotal GemFire [client](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-security-client) and [server-side](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-security-server) security, which is part of the new [Annotation config model](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config).  

More general information about configuring Security in Pivotal GemFire using _Spring Data GemFire_, begins [here](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-security).

But effectively, SDG now provides a [default implementation](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/support/AutoConfiguredAuthenticationInitializer.html) of the [`o.a.g.security.AuthInitialize`](http://gemfire-92-javadocs.docs.pivotal.io/org/apache/geode/security/AuthInitialize.html) interface.

Using this new Security annotation support in SDG for _Spring Boot_, Pivotal GemFire `ClientCache` applications, is as simple as the following...

````
@SpringBootApplication
@ClientCacheApplication
@EnableSecurity
class MySpringBootPivotalGemFireCacheClientApplication {

    public static void main(String[] args) {
        SpringApplication.run(MySpringBootPivotalGemFireCacheClientApplication.class, args);
    }
}
````

Thus, annotate the _Spring Boot_ main application class with SDG's `@EnableSecurity` annotation, and then set the `username` and `password` properties to authenticate the client in _Spring Boot's_ `application.properties`...

```
#application.properties

spring.data.gemfire.security.username=MyUser
spring.data.gemfire.security.password=MyPassword

...
````

Inside of PCF, when pushing and deploying your Pivotal GemFire-based, _Spring Boot_ application, you will not need to explicitly define `username` and `password` properties in `application.properties`.

_Spring Boot Data GemFire_ will effectively be able to extract this information from the VCAP environment variables created by PCF when a _Spring Boot_ application is deployed.

More to come...

**Comment by jxblum** [comment]
Spring Boot **auto-configuration** of either Apache Geode or Pivotal GemFire Security, securing a client connecting to a server in either a local, non-managed environment (i.e. standalone) as well as a cloud, managed environment (e.g. PCF) is complete!
