### ISSUE TITLE
SBDG Fails in Docker

### ISSUE THREAD

**Issue by nayakmk** [spring-projects/spring-boot-data-geode#120]
Hi Team, 

I am trying to just have 'org.springframework.geode:spring-geode-starter' in my buid.gradle and now trying to dockerize the application. This runs fine locally if I run as spring boot applicaiton but the jar is not running in docker and neither any logs are coming up.

If I exlude this dependency, the docker container starts fine. 

Is there something I am missing ?

```
ext {
	set('springGeodeVersion', "1.7.4")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.geode:spring-geode-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

Dockerfile is as simple as:

```
FROM openjdk:17-oracle
COPY build/libs/demo-0.0.1-SNAPSHOT.jar demo.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/demo.jar"]
```

**Comment by jxblum** [comment]
I'm afraid this is not a lot of information to go on.

To start with, it would be helpful to know how you are using _Spring Boot for Apache Geode_ (SBDG) in your _Spring Boot_ application?  For example, is your _Spring Boot_ application an Apache Geode [client](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-clientcache-applications) (i.e. `ClientCache`) or an embedded, [peer `Cache` application](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-peercache-applications), or even some other type of server node (e.g. a [Locator](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-locator-applications) or [Manager](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-manager-applications) perhaps)? 

What does the configuration for the Apache Geode components in your Spring Boot application consist of? What features of Apache Geode are you specifically trying to use?

Can you share any log files?

Have you tried to take a **Thread dump** of the _Spring Boot_, Apache Geode application running in Docker? This will help identify which Threads are busy doing what. Apache Geode startups up many, many Threads (using ThreadPools and Executors) during its normal operation, along with allocating many ports for communication. It is more likely that Apache Geode got hung up some where in the startup process than it being something in _Spring Boot_, or an SBDG problem in particular. But, without a Thread dump, it is difficult to pinpoint the problem to 1 thing.

It is unlikely SBDG is not working in Docker at all, and more likely there is a conflict between the Docker container / Docker engine and your host environment, which is what?

The nightly CI build for SBDG runs on Jenkins in Docker containers. SBDG's test suites cover all manners of using Apache Geode in different capacities (client/server, embedded, WAN) along with many of its features (basic Gets/Puts, Persistence, Caching, CQ, Functions, Persistence, Security).

Have you seen the [chapter](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-docker) on using SBDG and Apache Geode in Docker?

Are you able to share a simple SBDG app that can reproduce the problem? This would also help with during further analysis on our side.

Thanks!

**Comment by jxblum** [comment]
Preferably, I'd also say it would be better to package your entire Spring Boot application (and dependencies) into a single (fat) Spring Boot application JAR file, built as a Docker image and ran in a Docker container.

**Comment by jxblum** [comment]
Thank you for sharing more details, Malaya. This is already helpful.

To get a you a bit further, it would seem that the SBDG auto-configuration for SSL Sockets (connections) is perhaps problematic in a Docker (container) environment, for some reason, as can be seen with the "main" Thread:

```
"main" #1 prio=5 os_prio=0 cpu=597955.87ms elapsed=599.47s tid=0x00007f45780238a0 nid=0x8 runnable  [0x00007f457edaa000]
   java.lang.Thread.State: RUNNABLE
  java.lang.Thread.State: RUNNABLE
	at java.io.UnixFileSystem.getBooleanAttributes0(java.base@17.0.2/Native Method)
	at java.io.UnixFileSystem.hasBooleanAttributes(java.base@17.0.2/UnixFileSystem.java:269)
	at java.io.File.isDirectory(java.base@17.0.2/File.java:865)
	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.isDirectory(SslAutoConfiguration.java:252)
	at org.springframework.geode.boot.autoconfigure.SslAutoConfiguration.locateKeyStoreInFileSystem(SslAutoConfiguration.java:217)
```

This could have something to do with how the Docker container itself is configured (e.g. ports or mapping access from host UNIX/Linux based files to the Docker container files, etc), although I cannot say that for certain yet.

So, temporarily, you can actually disable the auto-configuration for SSL with a "secret" System property on application startup.  Specifically:

`spring.boot.data.gemfire.security.ssl.environment.post-processor.enabled`

See [here](https://github.com/spring-projects/spring-boot-data-geode/blob/1.7.5/spring-geode-autoconfigure/src/main/java/org/springframework/geode/boot/autoconfigure/SslAutoConfiguration.java#L98-L99), then [here](https://github.com/spring-projects/spring-boot-data-geode/blob/1.7.5/spring-geode-autoconfigure/src/main/java/org/springframework/geode/boot/autoconfigure/SslAutoConfiguration.java#L293-L306) and finally, [here](https://github.com/spring-projects/spring-boot-data-geode/blob/1.7.5/spring-geode-autoconfigure/src/main/java/org/springframework/geode/boot/autoconfigure/SslAutoConfiguration.java#L92).

Of course, you can simply use the Spring Boot way to disable specific auto-configuration classes as well:

See the [docs](https://docs.spring.io/spring-boot-data-geode-build/current/reference/html5/#geode-auto-configuration-disable). In this case, the configuration would (roughly) be:

```java
@SpringBootApplication(exclude = SSLAutoConfiguration.class)
public class MySpringBootApacheGeodeClientDockerApplication {

    public static void main(String[] args) {
        SpringApplication.run(MySpringBootApacheGeodeClientDockerApplication.class);
    }
}
```

Looking at the 'main' Thread dump and the [line from SBDG](https://github.com/spring-projects/spring-boot-data-geode/blob/1.7.5/spring-geode-autoconfigure/src/main/java/org/springframework/geode/boot/autoconfigure/SslAutoConfiguration.java#L252) specifically in question (252):

```
https://github.com/spring-projects/spring-boot-data-geode/blob/1.7.5/spring-geode-autoconfigure/src/main/java/org/springframework/geode/boot/autoconfigure/SslAutoConfiguration.java#L252
```

It is clear that the UNIX/Linux and Windows based Docker environment managed from Kubernetes is having some trouble with deciding whether the `File` object is a valid directory or not (jeepers):

```
	at java.io.UnixFileSystem.getBooleanAttributes0(java.base@17.0.2/Native Method)
	at java.io.UnixFileSystem.hasBooleanAttributes(java.base@17.0.2/UnixFileSystem.java:269)
	at java.io.File.isDirectory(java.base@17.0.2/File.java:865)
```

Something in the implementation of the `java.io.UnixFileSystem.getBooleanAttributes(..)` method is not playing nicely in a UNIX/Linux and Windows based Docker env.

**Comment by jxblum** [comment]
I forgot to mention this before, but SBDG `1.7.x` (based on Apache Geode `1.14.x`) is **not** officially certified to work with **Java 17**, as you have configured in Docker:

```
FROM openjdk:17-oracle
...
```

This is more of an Apache Geode restriction than a SBDG restriction since Apache Geode before `1.15` (i.e. Apache Geode `1.14` and earlier) was only certified to run on **Java 8** and **Java 11**.  Only Apache Geode `1.15` was specifically tested and verified by the Apache Geode community at ASF on **Java 17**.

Even then, after I tested and finally got SBDG running with Apache Geode `1.15` on **Java 17**, there were still some considerable hurdles a user must jump through to get Apache Geode properly running and working on **Java 17**.

Technically, running Apache Geode `1.15` on **Java 17** is only supported by SBDG `2.0`, which is also based on _Spring Boot_ `3.0`, which up'd the baseline across the Spring portfolio to Java 17 (starting with _Spring Framework_ 6), and thus, requiring all 3rd party dependencies in which _Spring_ integrates with to also build and run on **Java 17**.

> TIP: See the SBDG [Version Compatibility Matrix](https://github.com/spring-projects/spring-boot-data-geode/wiki/Spring-Boot-for-Apache-Geode-and-VMware-Tanzu-GemFire-Version-Compatibility-Matrix#version-compatibility-matrix) for version details.

In short, Apache Geode requires specific things to be "open" in the Java Module System introduced in Java 9 and enforced in Java 17. This might actually explain some of the problems you are currently experiencing.

For instance, when testing (in SBDG, and even SDG for that matter), I explicitly need to [explicitly declare these](https://github.com/spring-projects/spring-test-data-geode/blob/1.0.0-M7/spring-data-geode-test/src/main/java/org/springframework/data/gemfire/tests/process/ProcessExecutor.java#L172-L190-) `--add-opens` JVM options.

Unfortunately, and FYI, all development of S*DG (e.g. SBDG) on Apache Geode `1.15` has come to a halt.

This means the Spring team will not be releasing nor supporting any bits compatible with Apache Geode `1.15` on **Java 17**.

See the recent [NOTICE](https://github.com/spring-projects/spring-data-geode#notice) for more details.

**Comment by jxblum** [comment]
1 last thing...

You have look at the Docker configuration used by the SBDG Jenkins CI build, [here](https://github.com/spring-projects/spring-boot-data-geode/blob/main/Jenkinsfile#L29) and [here](https://github.com/spring-projects/spring-boot-data-geode/blob/main/ci/pipeline.properties).

Specifically, [this](https://github.com/spring-projects/spring-boot-data-geode/blob/main/ci/pipeline.properties#L9).

Not sure this will help much though.

Definitely trying to run Apache Geode `1.14.x` (or earlier), which is what SBDG `1.7.x` pulls in transitively by default, on **Java 17**, is not going to work in the long run.

Unfortunately, upgrading SBDG `1.7.x` to Apache Geode `1.15` is problematic too since several APIs in Apache Geode required by SBDG have changed.

**Comment by jxblum** [comment]
HI @nayakmk - I am going to close out this ticket for the time being. If you have any other issues, feel free reach out by re-opening this ticket or filing a new ticket.

**Comment by sshivar** [comment]
Deploying an application in AWS ECS using gemfire with embedded cache getting below exception 

ERROR [wm-inv-aggr-aladnutil,,] o.a.g.i.cache.InternalCacheBuilder [] java.lang.RuntimeException: java.io.IOException: Unable to write to deploy directory:

Caused by: java.lang.RuntimeException: Error occurred while initializing the cache

2023-10-24T19:07:14.984+05:30                at org.springframework.data.gemfire.util.RuntimeExceptionFactory.newRuntimeException(RuntimeExceptionFactory.java:119)

2023-10-24T19:07:14.984+05:30                at org.springframework.data.gemfire.AbstractResolvableCacheFactoryBean.init(AbstractResolvableCacheFactoryBean.java:79)

2023-10-24T19:07:14.984+05:30

Copy
                at org.springframework.data.gemfire.AbstractResolvableCacheFactoryBean.doGetObject(AbstractResolvableCacheFactoryBean.java:52)
at org.springframework.data.gemfire.AbstractResolvableCacheFactoryBean.doGetObject(AbstractResolvableCacheFactoryBean.java:52)

2023-10-24T19:07:14.984+05:30                at org.springframework.data.gemfire.AbstractBasicCacheFactoryBean.getObject(AbstractBasicCacheFactoryBean.java:351)

2023-10-24T19:07:14.984+05:30                at org.springframework.data.gemfire.AbstractBasicCacheFactoryBean.getObject(AbstractBasicCacheFactoryBean.java:113)

2023-10-24T19:07:14.984+05:30                at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)

2023-10-24T19:07:14.984+05:30                ... 75 common frames omitted

2023-10-24T19:07:14.984+05:30                Caused by: java.lang.RuntimeException: java.io.IOException: Unable to write to deploy directory: /
