### ISSUE TITLE
@ClientCacheApplication - Overrides log

### ISSUE THREAD

**Issue by ranishwetha** [spring-projects/spring-boot-data-geode#18]
`@ClientCacheApplication` overrides my logger settings.  None of my log4j information is carried since I have declared this. 

In my application, I don't need client cache either.  Is there a way to avoid using this? Kindly advise?

**If I comment on this line I get below error -**

Consider defining a bean named 'gemfireCache' in your configuration

Changes made:

```java
@Configuration
// @ClientCacheApplication(name = "GemFireClientCacheApplication", durableClientId = "store", keepAlive = true, readyForEvents = true, subscriptionEnabled = true)**
@EnableGemfireCaching
@EnableSecurity
@EnablePdx
public class GemfireConfiguration {

}
```

**Log shows the override.**  Please let me know if how I can avoid it.

```
Log4J 2 Configuration:
2018-12-06T20:11:26.807-05:00 [APP/PROC/WEB/0] [OUT] jar:file:/home/vcap/app/BOOT-INF/lib/geode-core-9.1.1.jar!/log4j2.xml
```

**Comment by ranishwetha** [comment]
If I comment on this line I get below error -

Consider defining a bean named 'gemfireCache' in your configuration

Changes made:

@Configuration
//@ClientCacheApplication(name = "GemFireClientCacheApplication", durableClientId = "store", keepAlive = true, readyForEvents = true, subscriptionEnabled = true)
@EnableGemfireCaching
@EnableSecurity
@EnablePdx
public class GemfireConfiguration {

}

**Comment by ranishwetha** [comment]
Log shows the override. Please let me know if how I can avoid it.
Log4J 2 Configuration:
2018-12-06T20:11:26.807-05:00 [APP/PROC/WEB/0] [OUT] jar:file:/home/vcap/app/BOOT-INF/lib/geode-core-9.1.1.jar!/log4j2.xml

**Comment by ranishwetha** [comment]
Hi, any update or observation on this?

**Comment by jxblum** [comment]
Hi @ranishwetha -

Alright, where to begin?

1) First, you state...

> _In my application, I don't need client cache either. Is there a way to avoid using this?_

What do you mean by, "I do not need a `ClientCache`?"  

Why would you use  **_Spring Boot for Pivotal GemFire_** (SBDG) in the first place if you did not need a `ClientCache` (?), where it would seem you are deploying your _Spring Boot_ app to PCF and using PCC (??).  In order to connect to a PCC cluster in PCF, you need a `ClientCache` instance?  If you have defined GemFire objects (e.g. _Regions_) in your application configuration to manage your data, then those objects require a cache instance. 

It would also seem your are using PCC as a "_caching provider_" / backing store for the implied use of  _Spring's Cache Abstraction_ in your application given the declaration of the `@EnableGemfireCaching` annotation.

Given the above, this is why you getting the follow error message by _Spring Boot_ on startup:

`Consider defining a bean named 'gemfireCache' in your configuration`

2) Second, when using **_Spring Boot for Pivotal GemFire_** (SBDG), you do **not** need to "explicitly" annotate your application configuration class (i.e. `GemFireConfiguration`) with any of: `@ClientCacheApplication`, `@EnableGemfireCaching`, `@EnablePdx` nor `@EnableSecurity` since, OOTB, SBDG provides _auto-configuration_ for all of these features.

SBDG provides you with a `ClientCache` instance, by default.  It also enables PDX, by default.  It can detect the context in which your app is deployed/running (e.g. PCF when using PCC) and automatically apply the necessary/required Security settings, by default.  And, when either Apache Geode or Pivotal GemFire is on your application's classpath, then SBDG will automatically use GemFire or Geode as a "_caching provider_" in _Spring's Cache Abstraction_, by default.

You typically do not declare any of the SDG's 3 cache type annotations [`@ClientCacheApplication`, `@PeerCacheApplication`, `@CacheServerApplication`] when using SBDG unless you want to A) override the cache type (again, a `ClientCache` by default) to use another type of cache (e.g. a "peer" cache instance when you want your application to be "peer" member of the GemFire/PCC cluster, which is rare) or B) you want to supply custom, very-specific cache configuration (e.g. `subscriptionEnabled = true` on the client).

Of course, there are other ways to accomplish the later (B), i.e. supplying additional, custom cache configuration, either by way of [Properties](https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#bootstrap-annotation-config-properties) or using a [Configurer](https://docs.spring.io/spring-data/gemfire/docs/current/reference/html/#bootstrap-annotation-config-configurers) bean.

To get a these "default" features out of the box, you simply only need to declare `org.springframework.geode:spring-gemfire-starter` in your application dependencies, thereby adding the LIB to your application's classpath at runtime.

3) Third, you do not need to specifically annotate your application configuration class with `@Configuration` either, since the `@ClientCacheApplication` annotation, or even _Spring Boot's_ `@SpringBootApplication` annotation is already (indirectly) meta-annotated with `@Configuration`.  For [instance](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/ClientCacheApplication.html).

The only annotations you need in your case to get started, really, is...

```java
@SpringBootApplication
class MySpringBootApplication { .. }
```

... again, providing the `org.springframework.geode.spring-gemfire-starter` dependency (LIB) is on your application's classpath at runtime.

Done!

4) Finally, as for logging...

Neither the `@ClientCacheApplication` annotation, nor SDG in general, prevent you from customizing the logging for the a GemFire client or server itself.

Under the hood, Pivotal GemFire/PCC (and by extension, Apache Geode) uses the **Log4j** framework as its logging facade and implementation.  Therefore, you can supply the logging configuration for a GemFire/PCC app by following the [documentation](http://gemfire.docs.pivotal.io/96/geode/managing/logging/configuring_log4j2.html).

The `@ClientCacheApplication` annotation simply gives you the ability to affect the [`logLevel`](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/ClientCacheApplication.html#logLevel--).

And, since you do not explicitly need to specify the `@ClientCacheApplication` annotation in a SBDG application, and thus have no direct way to set `logLevel` by way of the `@ClientCacheApplication` annotation `logLevel` attribute, SDG provides the [`@EnableLogging` annotation](https://docs.spring.io/spring-data/geode/docs/current/api/org/springframework/data/gemfire/config/annotation/EnableLogging.html), which implies [this setup](http://gemfire.docs.pivotal.io/96/geode/managing/logging/setting_up_logging.html).

Either way, it seems in your case, you should be following the "advice" in the opening paragraphs, [here](http://gemfire.docs.pivotal.io/96/geode/managing/logging/configuring_log4j2.html).

Hope this helps!

Regards,
@jxblum

**Comment by ranishwetha** [comment]
Thanks John! This is helpful.
