### ISSUE TITLE
Please rename the project to make it clear that it's not part of Spring Boot

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-boot-data-geode#2]
As [described in Spring Boot's documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-starter) we prefer to keep the `spring-boot-*` naming for modules that are part of Spring Boot. As this project will be an add-on, something like `data-gemfire-spring-boot` would be a more appropriate, and less confusing, name.

**Comment by jxblum** [comment]
I have changed the project name to "_Spring Boot for Apache Geode_" along with "_Spring Boot for Pivotal GemFire_".  This will be how I refer to this project publicly, at least.

The GitHub Repository name will remain as `spring-boot-data-geode`.

The Maven artifacts will be `org.springframework.boot:gemfire-spring-boot-starter` and `org.springframework.boot:geode-spring-boot-starter`, respectively.

Although, I am open to suggestions on the `groupId` as well (which I currently have set to `org.springframework.boot`).  I am somewhat partial to the `org.springframework.boot` namespace (and `groupId`) since this is consistent with the way we are handling _Spring Session_.  For instance, _Spring Session Data GemFire_ is [`org.springframework.session:spring-session-data-gemfire`](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-session-data-gemfire%22) and _Spring Session Data MongoDB_ is [`org.springframework.session:spring-session-data-mongodb`](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-session-data-mongodb%22).

**Comment by jxblum** [comment]
These changes were committed to `master` in revision [fdcaeaf](https://github.com/spring-projects/spring-boot-data-geode/commit/fdcaeaff1b85c93846881c037b2ac4cdbd1f951e).

**Comment by wilkinsona** [comment]
The new artifact IDs are great. Thanks. Can you please change the group ID too? `org.springframework.boot` should only be used for modules that are part of Boot and not for add-ons.
