### ISSUE TITLE
Consider removing JSR-107 - JCache API dependency from starters

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-boot-data-geode#45]
Adding JCache in the starter looks a bit unusual to me and I'd like to know more about it. A typical Spring Boot application will react based on choices made by the user and it's not obvious to me why using geode means they want to use JCache.

**Comment by jxblum** [comment]
JSR-107, _JCache_ API is a dependency required by SDG at present.  SDG needs to be refactored to not require the _JCache_ libs, by default, especially if the _JCache_ libs and API are not present in the user's application classpath.

See [SGF-808](https://jira.spring.io/browse/SGF-808) for more details.

**Comment by snicoll** [comment]
Thanks for the feedback. 

In the same topic, I am also wondering why the cache infrastructure is bootstrapped by default? In a typical Spring Boot app, caching does not happen unless you add `@EnableCaching` to your app.  Given the starter covers several different use cases, can you please explain why this one works differently (i.e. if you add spring data redis, you don't get caching unless you ask for it).

**Comment by jxblum** [comment]
Regarding "_auto-configuration_" for caching, enabling Apache Geode (or Pivotal GemFire) to be a _caching provider_ in _Spring's Cache Abstraction_...

Well, it fundamentally boils down to that we want users to:

1. Move from Open Source (Apache Geode) to commercial (Pivotal Cloud Cache (PCC)), and...
2. Move from non-managed environments (standalone Apache Geode clusters) to managed environments (Pivotal CloudFoundry using PCC), with...
3. Little to no code or configuration changes.

And... _Look-Aside Caching_ is the [**primary** UC](https://content.pivotal.io/blog/an-introduction-to-look-aside-vs-inline-caching-patterns) for PCC.

It is actually, quite a bit more involved then what I just described above, but we'll leave it at that for now.

Essentially, I want to enable users with as many "_auto-configured_" capabilities OOTB as possible, so that they can get up and run as quickly, easily and reliably as possible.

1) Caching (_Look-Aside_, _Inline_, _Near_, and soon... _Multi-Site_)
2) System of Record (using SD _Repositories_)
3) Distributed Compute (Functions)
4) Real-time, Event Stream Processing (CQs)
5)  Security (Auth & TLS)
6) Session state caching
7) Serialization
8) etc...

Comparing Redis to GemFire/Geode is like comparing apples to grapes.

Anyway, FWIW.

**Comment by jxblum** [comment]
Also see [DATAGEODE-225](https://jira.spring.io/browse/DATAGEODE-225).

**Comment by snicoll** [comment]
> Comparing Redis to GemFire/Geode is like comparing house cats to tigers. 

I wasn't doing that. I was comparing one store with another and how they behave with regards to caching.

> Essentially, I want to enable users with as many "auto-configured" capabilities OOTB as possible, so that they can get up and running as quickly, and easily, and reliably as possible, for whatever their application concern(s) or UCs might be.

I have no problem with that as long as the signal that the user wants to use the feature is explicit enough. There are various mechanism that can be used, the most common being the presence of a given library on the classpath. Caching is quite different here as most providers can be used for caching and something else. 

> Spring Boot for Apache Geode's (SBDG) "auto-configuration" is also quite a bit more extensive then any other SD module for that matter

I wasn't comparing this project with a "regular" SpringData module either. I am merely reporting that, from a Spring Boot perspective, enabling features without proper signal from the use is something we try to avoid as much as possible.

**Comment by jxblum** [comment]
@snicoll - Understood.

**Comment by jxblum** [comment]
1 more thing regarding your [response](https://github.com/spring-projects/spring-boot-data-geode/issues/45#issuecomment-523929294) to my [comments](https://github.com/spring-projects/spring-boot-data-geode/issues/45#issuecomment-523747768) above:

1) From my perspective, I have sent the proper signals, or simply, have properly communicated what SBDG give you OOTB, i.e. what _auto-configuration_ is applied by default in both the [README](https://github.com/spring-projects/spring-boot-data-geode#project-goals) as well as the [Introduction](https://docs.spring.io/spring-boot-data-geode-build/1.1.x/reference/html5/#introduction) in the [Documentation](https://docs.spring.io/spring-boot-data-geode-build/1.1.x/reference/html5/).

2) Just a friendly reminder, I have also taken steps (for example, [this](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-autoconfigure/src/test/java/org/springframework/geode/boot/autoconfigure/caching/ManuallyConfiguredCachingIntegrationTests.java) and [this](https://github.com/spring-projects/spring-boot-data-geode/blob/master/spring-geode-autoconfigure/src/test/java/org/springframework/geode/boot/autoconfigure/caching/ManuallyConfiguredWithPropertiesCachingIntegrationTests.java)) to ensure that SBDG quietly and properly backs away when users have expressed their "explicit interests" in configuration, which provider they want to use for _caching_.

Let me know if you have additional concerns.
